name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      
      - name: Run tests
        run: ./gradlew test --no-daemon
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/
      
      - name: Publish to Gitea Maven
        if: github.ref == 'refs/heads/main'
        env:
          GITEA_USER: ${{ secrets.GITEA_USER }}
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: ./gradlew publishAllPublicationsToGiteaRepository --no-daemon
      
      - name: Publish to GitHub Packages
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository --no-daemon

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.rokkon.com
          username: ${{ secrets.GITEA_USER }}
          password: ${{ secrets.GITEA_TOKEN }}
      
      - name: Build and push Docker image
        env:
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.GITEA_USER }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.GITEA_TOKEN }}
        run: |
          ./gradlew build \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            --no-daemon
      
      - name: Tag with commit SHA
        run: |
          docker tag git.rokkon.com/io-pipeline/platform-registration-service:latest \
                     git.rokkon.com/io-pipeline/platform-registration-service:${{ github.sha }}
          docker push git.rokkon.com/io-pipeline/platform-registration-service:${{ github.sha }}

