name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test with Gradle
        run: ./gradlew clean build test --no-daemon

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/

      - name: Publish to Reposilite and Gitea
        if: gitea.ref == 'refs/heads/main'
        env:
          REPOS_PAT: ${{ secrets.REPOS_PAT }}
          REPOS_USER: ${{ secrets.GIT_USER }}
        run: ./gradlew publish --no-daemon

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: gitea.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.rokkon.com
          username: ${{ secrets.GIT_USER }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and push Docker image with Quarkus
        env:
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.GIT_USER }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.GIT_TOKEN }}
          REPOS_PAT: ${{ secrets.REPOS_PAT }}
        run: |
          ./gradlew build \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.additional-tags=${{ gitea.sha }} \
            --no-daemon
